(() => {
  "use strict";
  const D = window.DEMO_DATA;
  const STORE = "learnatoriumPrincipalDemoV1";
  const icons = {Dashboard:"speedometer2",Students:"people",Attendance:"clipboard2-check",Academics:"mortarboard",Timetable:"calendar3",Homework:"journal-text",Exams:"bar-chart",Fees:"wallet2",Announcements:"megaphone",Calendar:"calendar-event",Teachers:"person-workspace",Reports:"pie-chart",Transport:"bus-front",Admissions:"person-plus",Library:"bookshelf"};
  const navMain = ["Dashboard","Students","Attendance","Academics","Timetable","Homework","Exams","Fees","Announcements","Calendar","Teachers","Reports"];
  const future = ["Transport","Admissions","Library"];
  let state = loadState();
  let currentView = state.role === "Principal" ? "Dashboard" : "Dashboard";
  let charts = [];
  let modal;

  function freshState(){ return {role:"Principal",childId:"student-1",attendance:structuredClone(D.attendance),homework:structuredClone(D.homework),announcements:structuredClone(D.announcements),payments:{}}; }
  function loadState(){ try { const saved=JSON.parse(localStorage.getItem(STORE)); return saved && saved.role ? {...freshState(),...saved} : freshState(); } catch { return freshState(); } }
  function persist(){ localStorage.setItem(STORE,JSON.stringify(state)); }
  function esc(value){ return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]); }
  function money(n){ return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n); }
  function initials(name){ return name.split(" ").map(x=>x[0]).slice(0,2).join(""); }
  function destroyCharts(){ charts.forEach(c=>c.destroy()); charts=[]; }
  function roleUser(){ return state.role==="Principal"?{name:"Principal",label:"School Management",initials:"PR"}:state.role==="Teacher"?{name:"Ms. Priya",label:"Teacher",initials:"MP"}:{name:"Farah Hussain",label:"Parent",initials:"FH"}; }

  function header(){ const u=roleUser(); return `<header class="app-header"><div class="d-flex align-items-center gap-2"><button class="icon-button d-md-none" data-action="mobile-menu" aria-label="Open menu"><i class="bi bi-list"></i></button><img class="brand-logo" src="assets/logo/learnatorium-logo.png" alt="Learnatorium Primary School"></div><div class="header-tools"><button class="icon-button" aria-label="Notifications" data-view="Announcements"><i class="bi bi-bell"></i><span class="notification-dot"></span></button><label class="d-flex align-items-center gap-2"><span class="small text-muted desktop-only">View As</span><select id="roleSwitcher" class="role-switch" aria-label="View application as"><option ${state.role==="Principal"?"selected":""}>Principal</option><option ${state.role==="Teacher"?"selected":""}>Teacher</option><option ${state.role==="Parent"?"selected":""}>Parent</option></select></label><div class="user-meta text-end"><strong>${u.name}</strong><small class="d-block text-muted">${u.label}</small></div><div class="dropdown"><button class="avatar border-0" data-bs-toggle="dropdown" aria-label="User menu">${u.initials}</button><ul class="dropdown-menu dropdown-menu-end shadow border-0"><li><button class="dropdown-item" data-action="reset"><i class="bi bi-arrow-counterclockwise me-2"></i>Reset Demo Data</button></li></ul></div></div></header>`; }
  function sidebar(){ return `<aside class="app-sidebar"><div class="nav-label">School Management</div>${navMain.map(n=>`<button class="side-link ${currentView===n?"active":""}" data-view="${n}"><i class="bi bi-${icons[n]}"></i><span>${n}</span></button>`).join("")}<div class="nav-label mt-3">Future Modules</div>${future.map(n=>`<button class="side-link ${currentView===n?"active":""}" data-view="${n}"><i class="bi bi-${icons[n]}"></i><span>${n}</span><span class="soon">Soon</span></button>`).join("")}</aside>`; }
  function mobileMenu(){ return `<div class="offcanvas offcanvas-start" tabindex="-1" id="mobileNav"><div class="offcanvas-header"><img src="assets/logo/learnatorium-logo.png" alt="Learnatorium" style="width:210px"><button class="btn-close" data-bs-dismiss="offcanvas"></button></div><div class="offcanvas-body">${[...navMain,...future].map(n=>`<button class="side-link ${currentView===n?"active":""}" data-view="${n}" data-bs-dismiss="offcanvas"><i class="bi bi-${icons[n]}"></i>${n}${future.includes(n)?'<span class="soon">Soon</span>':""}</button>`).join("")}</div></div>`; }
  function bottomNav(){ if(state.role!=="Parent")return ""; return `<nav class="parent-bottom-nav" aria-label="Parent navigation"><button class="${currentView==="Dashboard"?"active":""}" data-view="Dashboard"><i class="bi bi-house"></i>Home</button><button class="${["Academics","Exams","Timetable"].includes(currentView)?"active":""}" data-view="Academics"><i class="bi bi-mortarboard"></i>Academics</button><button class="${currentView==="Announcements"?"active":""}" data-view="Announcements"><i class="bi bi-chat-left-text"></i>Inbox</button><button data-action="parent-more"><i class="bi bi-grid"></i>More</button></nav>`; }
  function layout(content){ const principal=state.role==="Principal"; return `${header()}${principal?sidebar():""}${mobileMenu()}<main class="app-main ${principal?"with-sidebar":""}"><div class="page-shell fade-view">${content}</div></main>${bottomNav()}<div class="demo-ribbon"><i class="bi bi-stars me-1"></i>Presentation Demo</div>`; }
  function pageHead(title,subtitle,action=""){return `<div class="page-head"><div><div class="eyebrow">${state.role} workspace</div><h1 class="page-title">${title}</h1><p class="page-subtitle">${subtitle}</p></div>${action}</div>`;}
  function panel(title,body,tools=""){return `<section class="panel panel-pad"><div class="section-head"><h2 class="section-title">${title}</h2>${tools}</div>${body}</section>`;}
  function renderApp(){ destroyCharts(); let content;
    if(currentView==="Dashboard") content=state.role==="Principal"?principalDashboard():state.role==="Teacher"?teacherDashboard():parentDashboard();
    else if(currentView==="Students") content=studentsView();
    else if(currentView==="Attendance") content=state.role==="Teacher"?teacherAttendance():attendanceView();
    else if(currentView==="Homework") content=state.role==="Teacher"?teacherHomework():parentHomework();
    else if(currentView==="Announcements") content=announcementsView();
    else if(currentView==="Fees") content=feesView();
    else if(currentView==="Timetable"||currentView==="Calendar") content=timetableView();
    else if(currentView==="Academics"||currentView==="Exams") content=examsView();
    else if(currentView==="Reports") content=reportsView();
    else if(future.includes(currentView)) content=comingSoon(currentView);
    else content=genericView(currentView);
    document.getElementById("app").innerHTML=layout(content); requestAnimationFrame(initCharts); window.scrollTo({top:0,behavior:"smooth"});
  }

  function principalDashboard(){ const cards=[['people-fill','Students Present','451 / 482','93.6%',94],['person-badge-fill','Teachers Present','32 / 34','94.1%',94],['wallet-fill','Fee Collection','₹31.8L / ₹42.5L','74.8%',75],['calendar-check-fill',"Today's Classes",'112','On schedule',86]];
    const summary=cards.map(c=>`<article class="panel summary-card"><div class="d-flex justify-content-between"><div class="summary-icon"><i class="bi bi-${c[0]}"></i></div><span class="badge-soft ${c[1].includes('Present')?'badge-success':''}">${c[3]}</span></div><div class="summary-value">${c[2]}</div><div class="summary-label">${c[1]}</div><div class="progress-thin"><span style="width:${c[4]}%"></span></div></article>`).join("");
    const attention=['12 students absent today','7 overdue fee accounts','2 teachers on leave','Class VII-B attendance below 85%'].map((x,i)=>`<div class="attention-item"><span class="attention-icon"><i class="bi bi-${['person-x','wallet2','person-dash','graph-down-arrow'][i]}"></i></span><span>${x}</span><i class="bi bi-chevron-right"></i></div>`).join("");
    const events=D.events.map(e=>`<div class="event"><div class="date-chip"><strong>${e.date}</strong><span>${e.month}</span></div><div><strong>${e.title}</strong><small class="d-block text-muted mt-1">${e.meta}</small></div></div>`).join("");
    const announcements=visibleAnnouncements("Principal").slice(0,3).map(a=>`<div class="announcement-item"><span class="summary-icon"><i class="bi bi-megaphone"></i></span><div><strong>${esc(a.title)}</strong><small class="d-block text-muted">${esc(a.message)}</small><small class="text-brand">${esc(a.time)}</small></div></div>`).join("");
    return `${pageHead('Good Morning, Principal 👋',"Here's what's happening at Learnatorium Primary School today.",'<button class="btn btn-brand" data-action="new-announcement"><i class="bi bi-megaphone me-2"></i>New announcement</button>')}<div class="summary-grid">${summary}</div><div class="dashboard-grid"><div class="d-grid gap-3">${panel('Attendance Overview','<div class="chart-box"><canvas id="attendanceChart"></canvas></div>','<select class="form-select form-select-sm" style="width:120px"><option>This Week</option></select>')}${panel('Recent Announcements',announcements||empty('No announcements','Published announcements will appear here.'),'<button class="btn btn-sm btn-soft" data-view="Announcements">View all</button>')}</div><div class="d-grid gap-3">${panel('Attention Required',attention)}${panel('Upcoming Events',events,'<button class="btn btn-sm btn-soft" data-view="Calendar">View Calendar</button>')}</div></div>`;
  }
  function initCharts(){ if(typeof Chart==="undefined")return; const a=document.getElementById("attendanceChart"); if(a) charts.push(new Chart(a,{type:"bar",data:{labels:["Monday","Tuesday","Wednesday","Thursday","Friday"],datasets:[{label:"Present",data:[94,93,96,92,94],backgroundColor:"#C8102E",borderRadius:7},{label:"Absent",data:[6,7,4,8,6],backgroundColor:"#E7E9EE",borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,max:100,ticks:{callback:v=>v+"%"},grid:{color:"#F0F1F3"}}},plugins:{legend:{position:"bottom",labels:{usePointStyle:true,boxWidth:8}}}}}));
    const p=document.getElementById("performanceChart"); if(p)charts.push(new Chart(p,{type:"line",data:{labels:Object.keys(D.exams.marks),datasets:[{label:"Score %",data:Object.values(D.exams.marks).map(x=>x*5),borderColor:"#C8102E",backgroundColor:"rgba(200,16,46,.09)",fill:true,tension:.35,pointBackgroundColor:"#F5AE00",pointRadius:4}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{min:50,max:100,ticks:{callback:v=>v+"%"}}},plugins:{legend:{display:false}}}}));
    const r=document.getElementById("reportChart"); if(r)charts.push(new Chart(r,{type:"doughnut",data:{labels:["Collected","Pending"],datasets:[{data:[31.8,10.7],backgroundColor:["#C8102E","#FFD76A"],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:"72%",plugins:{legend:{position:"bottom"}}}})); }

  function studentsView(){ return `${pageHead('Students','Search and review student profiles across classes.')}<section class="panel panel-pad"><div class="filters"><div class="search-box"><i class="bi bi-search"></i><input id="studentSearch" class="form-control" placeholder="Search name or admission number"></div><select id="classFilter" class="form-select"><option value="">All classes</option>${["Nursery","I","II","III","IV","V","VII"].map(x=>`<option>${x}</option>`).join("")}</select><select id="sectionFilter" class="form-select"><option value="">All sections</option><option>A</option><option>B</option></select><button class="btn btn-soft" data-action="clear-filters">Clear</button></div><div id="studentResults">${studentTable(D.students)}</div></section>`; }
  function studentTable(list){ if(!list.length)return empty("No students found.","Try changing your search or filters."); return `<div class="table-responsive table-card"><table class="table align-middle"><thead><tr><th>Student</th><th>Admission</th><th>Class</th><th class="hide-mobile">Attendance</th><th class="hide-mobile">Fees</th><th></th></tr></thead><tbody>${list.map(s=>`<tr><td><div class="d-flex align-items-center gap-2"><span class="initial">${initials(s.name)}</span><span class="student-name" data-student="${s.id}">${s.name}</span></div></td><td>${s.admission}</td><td>${s.className}-${s.section}</td><td class="hide-mobile"><span class="${s.attendance<85?'text-danger':'text-success'} fw-semibold">${s.attendance}%</span></td><td class="hide-mobile"><span class="badge-soft ${s.feeStatus==='Paid'?'badge-success':'badge-warning'}">${s.feeStatus}</span></td><td><button class="icon-button" data-student="${s.id}" aria-label="Open ${s.name}"><i class="bi bi-chevron-right"></i></button></td></tr>`).join("")}</tbody></table></div>`; }
  function filterStudents(){ const q=document.getElementById("studentSearch")?.value.toLowerCase()||"",cl=document.getElementById("classFilter")?.value||"",sec=document.getElementById("sectionFilter")?.value||""; const found=D.students.filter(s=>(s.name.toLowerCase().includes(q)||s.admission.toLowerCase().includes(q))&&(!cl||s.className===cl)&&(!sec||s.section===sec)); document.getElementById("studentResults").innerHTML=studentTable(found); }
  function renderStudentProfile(id){ const s=D.students.find(x=>x.id===id); if(!s)return; currentView="Students"; destroyCharts(); const body=`${pageHead(s.name,`Class ${s.className}-${s.section} · Roll No. ${s.roll} · Admission No. ${s.admission}`,'<button class="btn btn-soft" data-view="Students"><i class="bi bi-arrow-left me-2"></i>Students</button>')}<section class="panel overflow-hidden"><div class="profile-hero"><div class="profile-avatar">${initials(s.name)}</div><div><h2 class="mb-1">${s.name}</h2><div class="text-muted">Class ${s.className}-${s.section} · Roll No. ${s.roll}</div><span class="badge-soft mt-2">${s.admission}</span></div></div><ul class="nav nav-tabs px-3" role="tablist">${["Overview","Attendance","Academics","Fees"].map((x,i)=>`<li class="nav-item"><button class="nav-link ${i===0?'active':''}" data-bs-toggle="tab" data-bs-target="#profile${x}">${x}</button></li>`).join("")}</ul><div class="tab-content p-4"><div class="tab-pane fade show active" id="profileOverview"><div class="info-grid"><div class="info-block"><small>Guardian</small><strong>${s.guardian}</strong></div><div class="info-block"><small>Contact</small><strong>${s.contact}</strong></div><div class="info-block"><small>Class Teacher</small><strong>Ms. Priya</strong></div><div class="info-block"><small>Attendance</small><strong>${todayStatus(s.id)==="absent"?'Absent today':s.attendance+'%'}</strong></div><div class="info-block"><small>Recent activity</small><strong>Homework viewed</strong></div><div class="info-block"><small>Fee status</small><strong>${s.feeStatus}</strong></div></div></div><div class="tab-pane fade" id="profileAttendance">${attendanceSummary(s)}</div><div class="tab-pane fade" id="profileAcademics">${marksList(s.marks)}</div><div class="tab-pane fade" id="profileFees">${feeSummary(s.id)}</div></div></section>`; document.getElementById("app").innerHTML=layout(body); }
  function attendanceSummary(s){ const present=Math.round(s.attendance*.22),absent=22-present; return `<div class="summary-grid"><div class="info-block"><small>Monthly attendance</small><strong>September 2026</strong></div><div class="info-block"><small>Present</small><strong>${present} days</strong></div><div class="info-block"><small>Absent</small><strong>${absent} days</strong></div><div class="info-block"><small>Attendance</small><strong>${s.attendance}%</strong></div></div>`; }
  function marksList(marks){return Object.entries(marks).map(([k,v])=>`<div class="marks-row"><span>${k}</span><strong>${v} / 20</strong></div>`).join("");}
  function feeFor(id){const base=structuredClone(D.fees[id]||{annual:42000,paid:42000,pending:0,nextInstallment:0,due:"—"});const paid=state.payments[id]?.amount||0;base.paid+=paid;base.pending=Math.max(0,base.pending-paid);return base;}
  function feeSummary(id){const f=feeFor(id);return `<div class="info-grid"><div class="info-block"><small>Annual Fee</small><strong>${money(f.annual)}</strong></div><div class="info-block"><small>Paid</small><strong class="text-success">${money(f.paid)}</strong></div><div class="info-block"><small>Pending</small><strong class="text-brand">${money(f.pending)}</strong></div></div>`;}

  function teacherDashboard(){ const slots=[["08:00 – 08:45","English","III-A"],["08:50 – 09:35","EVS","III-A"],["10:00 – 10:45","Mathematics","IV-B"],["11:00 – 11:45","Computer","V-A"],["12:30 – 01:15","English","V-B"]]; return `<div class="teacher-shell"><section class="panel teacher-hero"><small>TEACHER</small><h1 class="mt-2">Good Morning, Ms. Priya 👋</h1><p class="mb-0 text-white-50">You have 5 classes scheduled today.</p><div class="mobile-stat-grid"><div class="mobile-stat"><strong>4</strong><span>My Classes</span></div><div class="mobile-stat"><strong>112</strong><span>Total Students</span></div><div class="mobile-stat"><strong>98.2%</strong><span>Attendance</span></div></div></section><div class="action-grid my-3"><button class="action-tile" data-view="Attendance"><i class="bi bi-clipboard2-check"></i>Attendance</button><button class="action-tile" data-view="Homework"><i class="bi bi-journal-plus"></i>Homework</button><button class="action-tile" data-view="Academics"><i class="bi bi-pencil-square"></i>Marks</button><button class="action-tile" data-view="Announcements"><i class="bi bi-megaphone"></i>Announcements</button></div>${panel("Today's Timetable",slots.map(x=>`<div class="timeline-slot"><strong>${x[0]}</strong><span class="timeline-dot"></span><div><strong>${x[1]}</strong><small class="d-block text-muted">Class ${x[2]}</small></div></div>`).join("")+'<button class="btn btn-brand w-100 mt-3" data-view="Attendance"><i class="bi bi-check2-square me-2"></i>TAKE ATTENDANCE</button>')}</div>`; }
  function teacherAttendance(){const roster=D.students.filter(s=>s.className==="II"&&s.section==="A");const rows=roster.map(s=>{const v=state.attendance.records[s.id]||"present";return `<div class="attendance-row"><div class="d-flex align-items-center gap-2"><span class="initial">${initials(s.name)}</span><div><strong>${s.name}</strong><small class="d-block text-muted">Roll ${s.roll}</small></div></div><div class="attendance-toggle"><button class="present ${v==='present'?'active':''}" data-attendance="present" data-id="${s.id}">Present</button><button class="absent ${v==='absent'?'active':''}" data-attendance="absent" data-id="${s.id}">Absent</button></div></div>`}).join("");return `<div class="teacher-shell">${pageHead('Take Attendance','Class II-A · Today','<button class="btn btn-soft" data-action="mark-all"><i class="bi bi-check-all me-1"></i>Mark All Present</button>')}<section class="panel panel-pad"><div id="attendanceSummary" class="badge-soft badge-success mb-3">${attendanceCount()}</div>${rows}<button class="btn btn-brand w-100 mt-4" data-action="save-attendance"><i class="bi bi-cloud-check me-2"></i>Save Attendance</button></section></div>`;}
  function attendanceCount(){const roster=D.students.filter(s=>s.className==="II"&&s.section==="A");const absent=roster.filter(s=>state.attendance.records[s.id]==="absent").length;return `${roster.length-absent} Present · ${absent} Absent`;}
  function todayStatus(id){return state.attendance.records[id]||"present";}
  function attendanceView(){if(state.role==="Parent")return parentAttendance();return `${pageHead('Attendance','Monitor school attendance and exceptions.')}<div class="summary-grid"><div class="panel summary-card"><div class="summary-label">School Average</div><div class="summary-value">93.6%</div></div><div class="panel summary-card"><div class="summary-label">Present Today</div><div class="summary-value">451</div></div><div class="panel summary-card"><div class="summary-label">Absent Today</div><div class="summary-value">31</div></div><div class="panel summary-card"><div class="summary-label">Below 75%</div><div class="summary-value">12</div></div></div>${panel('Weekly Overview','<div class="chart-box"><canvas id="attendanceChart"></canvas></div>')}`;}
  function parentAttendance(){const s=currentChild(),status=todayStatus(s.id);return `<div class="parent-shell">${pageHead('Attendance',s.name)}<section class="panel panel-pad"><div class="status-card"><div class="status-icon"><i class="bi bi-${status==='present'?'check2-circle':'x-circle'}"></i></div><div><small class="text-muted">Today's Attendance</small><h3 class="mb-0 text-capitalize">${status}</h3></div></div>${attendanceSummary(s)}</section></div>`;}

  function teacherHomework(){return `<div class="teacher-shell">${pageHead('Homework','Create and publish work for your classes.','<button class="btn btn-brand" data-action="new-homework"><i class="bi bi-plus-lg me-1"></i>Create Homework</button>')}${homeworkCards(state.homework)} </div>`;}
  function parentHomework(){const s=currentChild(),list=state.homework.filter(h=>h.className===s.className&&h.section===s.section);return `<div class="parent-shell">${pageHead('Homework',`${s.name} · ${s.className}-${s.section}`)}${homeworkCards(list)}</div>`;}
  function homeworkCards(list){if(!list.length)return `<section class="panel">${empty('No homework','There is no homework assigned right now.')}</section>`;return `<div class="d-grid gap-3">${list.map(h=>`<article class="panel panel-pad"><div class="d-flex justify-content-between gap-3"><div><span class="badge-soft">${esc(h.subject)}</span><h3 class="h5 mt-3 mb-1">${esc(h.title)}</h3><p class="text-muted mb-2">${esc(h.description)}</p><small><i class="bi bi-calendar3 me-1 text-brand"></i>Due ${esc(h.due)}</small></div><i class="bi bi-journal-text fs-2 text-brand"></i></div></article>`).join("")}</div>`;}

  function visibleAnnouncements(role=state.role){return state.announcements.filter(a=>a.audience==="Entire School"||(role==="Teacher"&&a.audience==="Teachers")||(role==="Parent"&&(a.audience==="Parents"||a.audience==="Class II")));}
  function announcementsView(){const list=visibleAnnouncements();return `${pageHead('Announcements','Important school updates in one place.',state.role==="Principal"?'<button class="btn btn-brand" data-action="new-announcement"><i class="bi bi-plus-lg me-1"></i>Publish announcement</button>':'')}<section class="panel panel-pad">${list.length?list.map(a=>`<article class="announcement-item"><span class="summary-icon"><i class="bi bi-megaphone"></i></span><div class="flex-grow-1"><div class="d-flex justify-content-between"><strong>${esc(a.title)}</strong><small class="text-muted">${esc(a.time)}</small></div><p class="text-muted mb-1">${esc(a.message)}</p><span class="badge-soft">${esc(a.audience)}</span></div></article>`).join(""):empty('No announcements','New school updates will appear here.')}</section>`;}

  function currentChild(){return D.students.find(s=>s.id===state.childId)||D.students[0];}
  function childSelector(){return `<select id="childSwitcher" class="form-select" style="width:auto">${D.children.map(c=>`<option value="${c.id}" ${state.childId===c.id?'selected':''}>${c.name} · ${c.classLabel}</option>`).join("")}</select>`;}
  function parentDashboard(){const s=currentChild(),status=todayStatus(s.id),hw=state.homework.find(h=>h.className===s.className&&h.section===s.section),f=feeFor(s.id),latest=visibleAnnouncements("Parent")[0];return `<div class="parent-shell"><section class="panel parent-hero"><div class="d-flex justify-content-between align-items-start position-relative"><div><small>MY CHILD</small><h1 class="mt-2 mb-1">${s.name}</h1><p class="mb-0 text-white-50">Class ${s.className}-${s.section} · Roll No. ${s.roll}</p></div>${childSelector()}</div></section><h2 class="h5 my-4">What do I need to know about my child today?</h2><div class="home-grid"><article class="panel status-card"><div class="status-icon"><i class="bi bi-${status==='present'?'check2-circle':'x-circle'}"></i></div><div><small class="text-muted">Today's Attendance</small><h3 class="h5 mb-0 text-capitalize">${status}</h3></div></article><article class="panel panel-pad"><small class="text-muted">Today's Homework</small>${hw?`<h3 class="h5 mt-2">${esc(hw.subject)} · ${esc(hw.title)}</h3><p class="mb-0 text-muted">${esc(hw.description)}</p>`:'<p class="mb-0 mt-2">No homework today</p>'}</article><article class="panel panel-pad"><small class="text-muted">Upcoming</small><h3 class="h5 mt-2">Science Test</h3><p class="mb-0 text-muted">Friday · Chapter 3</p></article><article class="panel panel-pad"><div class="d-flex justify-content-between"><div><small class="text-muted">Fee Status</small><h3 class="h5 mt-2 text-brand">${money(f.pending)} Pending</h3><p class="mb-0 text-muted">Next installment ${money(f.nextInstallment)}</p></div><button class="icon-button" data-view="Fees"><i class="bi bi-chevron-right"></i></button></div></article></div><div class="action-grid my-3"><button class="action-tile" data-view="Attendance"><i class="bi bi-calendar-check"></i>Attendance</button><button class="action-tile" data-view="Homework"><i class="bi bi-journal-text"></i>Homework</button><button class="action-tile" data-view="Fees"><i class="bi bi-wallet2"></i>Fees</button><button class="action-tile" data-view="Timetable"><i class="bi bi-calendar3"></i>Timetable</button></div>${panel('Latest Announcement',latest?`<div class="announcement-item"><span class="summary-icon"><i class="bi bi-megaphone"></i></span><div><strong>${esc(latest.title)}</strong><p class="text-muted mb-1">${esc(latest.message)}</p><small class="text-brand">${esc(latest.time)}</small></div></div>`:empty('No announcements','School updates will appear here.'))}</div>`;}

  function feesView(){const s=state.role==="Parent"?currentChild():D.students[0],f=feeFor(s.id),paid=state.payments[s.id];return `<div class="parent-shell">${pageHead('Fees',state.role==="Parent"?`${s.name} · Class ${s.className}-${s.section}`:'Student fee overview')}<div class="summary-grid"><article class="panel summary-card"><div class="summary-label">Annual Fee</div><div class="fee-amount">${money(f.annual)}</div></article><article class="panel summary-card"><div class="summary-label">Paid</div><div class="fee-amount text-success">${money(f.paid)}</div></article><article class="panel summary-card"><div class="summary-label">Pending</div><div class="fee-amount text-brand">${money(f.pending)}</div></article><article class="panel summary-card"><div class="summary-label">Next Installment</div><div class="fee-amount">${money(f.nextInstallment)}</div><small class="text-muted">Due ${f.due}</small></article></div>${paid?receiptHtml(paid):`<section class="panel panel-pad text-center"><i class="bi bi-shield-check fs-2 text-success"></i><h2 class="h5 mt-2">Secure fee payment</h2><p class="text-muted">This presentation uses a simulated payment. No actual transaction occurs.</p><button class="btn btn-brand" data-action="pay" ${f.pending===0?'disabled':''}><i class="bi bi-credit-card me-2"></i>PAY NOW · ${money(f.nextInstallment)}</button></section>`}</div>`;}
  function receiptHtml(p){return `<section class="panel panel-pad"><div class="receipt"><div class="d-flex justify-content-between align-items-start"><div><span class="badge-soft badge-success"><i class="bi bi-check-circle"></i>Payment Successful</span><h2 class="h4 mt-3">Demo Receipt</h2></div><i class="bi bi-receipt fs-2 text-brand"></i></div><hr><div class="row g-3"><div class="col-6"><small class="text-muted">Receipt No.</small><strong class="d-block">${p.receipt}</strong></div><div class="col-6"><small class="text-muted">Amount</small><strong class="d-block">${money(p.amount)}</strong></div></div><button class="btn btn-soft mt-3" data-action="receipt"><i class="bi bi-eye me-1"></i>View Receipt</button></div></section>`;}

  function timetableView(){const slots=["08:00","08:50","10:00","11:00","12:30","01:20"];return `${pageHead('Weekly Timetable','A clear view of the school week.')}<div class="timetable-grid">${Object.entries(D.timetable).map(([day,subjects])=>`<section class="day-column"><div class="day-title">${day}</div>${subjects.map((s,i)=>`<div class="period"><strong>${s}</strong><small>${slots[i]} · Period ${i+1}</small></div>`).join("")}</section>`).join("")}</div>`;}
  function examsView(){const total=Object.values(D.exams.marks).reduce((a,b)=>a+b,0),pct=total;return `${pageHead('Academics & Results','Track performance across assessments.','<select class="form-select" style="width:auto"><option>Periodic Test 1</option><option>Half Yearly</option><option>Periodic Test 2</option><option>Annual Exam</option></select>')}<div class="dashboard-grid"><section class="panel panel-pad"><div class="section-head"><h2 class="section-title">Student Results</h2><span class="badge-soft">Haider Hussain · II-A</span></div>${marksList(D.exams.marks)}<div class="info-grid mt-3"><div class="info-block"><small>Total</small><strong>${total} / 100</strong></div><div class="info-block"><small>Percentage</small><strong>${pct}%</strong></div><div class="info-block"><small>Grade</small><strong>A+</strong></div></div></section>${panel('Performance','<div class="chart-box"><canvas id="performanceChart"></canvas></div>')}</div>`;}
  function reportsView(){return `${pageHead('Reports','School insights prepared for decision-making.')}<div class="summary-grid"><div class="panel summary-card"><div class="summary-label">School Average</div><div class="summary-value">93.6%</div></div><div class="panel summary-card"><div class="summary-label">Highest Attendance</div><div class="summary-value">IV-A · 97.2%</div></div><div class="panel summary-card"><div class="summary-label">Lowest Attendance</div><div class="summary-value">VII-B · 83.4%</div></div><div class="panel summary-card"><div class="summary-label">Students Below 75%</div><div class="summary-value">12</div></div></div><div class="dashboard-grid">${panel('Fee Collection Report','<div class="chart-box"><canvas id="reportChart"></canvas></div><div class="info-grid mt-3"><div class="info-block"><small>Expected</small><strong>₹42.5L</strong></div><div class="info-block"><small>Collected</small><strong>₹31.8L</strong></div><div class="info-block"><small>Pending</small><strong>₹10.7L</strong></div></div>')}${panel('Available Reports','<div class="d-grid gap-2"><button class="btn btn-soft text-start"><i class="bi bi-calendar-check me-2"></i>Attendance Report</button><button class="btn btn-soft text-start"><i class="bi bi-wallet2 me-2"></i>Fee Collection Report</button><button class="btn btn-soft text-start"><i class="bi bi-graph-up me-2"></i>Class Performance Report</button></div>')}</div>`;}
  function comingSoon(name){const data={Transport:["Bus Routes","Driver Details","Student Stops","Live Tracking","Pickup Notifications"],Admissions:["Enquiry","Applications","Document Upload","Admission Processing"],Library:["Book Catalogue","Issue / Return","Student Library History","Overdue Books"]};return `<section class="panel coming-soon"><div class="coming-icon"><i class="bi bi-${icons[name]}"></i></div><div class="eyebrow">Planned for Phase 2</div><h1 class="page-title">${name} Management</h1><p class="page-subtitle mx-auto" style="max-width:520px">A focused ${name.toLowerCase()} experience is planned as the school platform grows.</p><div class="feature-list">${data[name].map(x=>`<span class="feature-pill"><i class="bi bi-check2 text-brand me-1"></i>${x}</span>`).join("")}</div></section>`;}
  function genericView(name){return `${pageHead(name,`${name} tools for Learnatorium Primary School.`)}<section class="panel coming-soon"><div class="coming-icon"><i class="bi bi-${icons[name]||'grid'}"></i></div><h2 class="h4">${name} overview</h2><p class="text-muted mb-0">This demo screen is ready for the next presentation scenario.</p></section>`;}
  function empty(title,text){return `<div class="empty-state"><i class="bi bi-inbox"></i><h3 class="h6 mt-3">${title}</h3><p class="mb-0">${text}</p></div>`;}

  function showToast(message){const id=`toast-${Date.now()}`;document.getElementById("toastRegion").insertAdjacentHTML("beforeend",`<div id="${id}" class="toast" role="status"><div class="d-flex"><div class="toast-body"><i class="bi bi-check-circle-fill text-success me-2"></i>${esc(message)}</div><button class="btn-close me-2 m-auto" data-bs-dismiss="toast"></button></div></div>`);const el=document.getElementById(id),t=new bootstrap.Toast(el,{delay:2600});el.addEventListener("hidden.bs.toast",()=>el.remove());t.show();}
  function openModal(html,size="modal-lg"){const dialog=document.querySelector("#appModal .modal-dialog");dialog.className=`modal-dialog modal-dialog-centered ${size}`;document.getElementById("modalContent").innerHTML=html;modal=bootstrap.Modal.getOrCreateInstance(document.getElementById("appModal"));modal.show();}
  function announcementModal(){openModal(`<form id="announcementForm"><div class="modal-header"><div><small class="eyebrow">Principal action</small><h2 class="modal-title h5">Publish Announcement</h2></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Title</label><input name="title" class="form-control mb-3" value="Gandhi Jayanti Holiday" required maxlength="80"><label class="form-label">Audience</label><select name="audience" class="form-select mb-3"><option>Entire School</option><option>Class II</option><option>Class III</option><option>Teachers</option><option>Parents</option></select><label class="form-label">Message</label><textarea name="message" class="form-control" rows="4" required>School will remain closed on 2 October.</textarea></div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal" type="button">Cancel</button><button class="btn btn-brand">Publish Announcement</button></div></form>`);}
  function homeworkModal(){openModal(`<form id="homeworkForm"><div class="modal-header"><div><small class="eyebrow">Teacher action</small><h2 class="modal-title h5">Create Homework</h2></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-6"><label class="form-label">Class</label><select name="className" class="form-select"><option>II</option><option>III</option><option>IV</option><option>V</option></select></div><div class="col-6"><label class="form-label">Section</label><select name="section" class="form-select"><option>A</option><option>B</option></select></div><div class="col-12"><label class="form-label">Subject</label><select name="subject" class="form-select"><option>Mathematics</option><option>English</option><option>EVS</option><option>Hindi</option><option>Computer</option></select></div><div class="col-12"><label class="form-label">Title</label><input name="title" class="form-control" value="Fractions Practice" required></div><div class="col-12"><label class="form-label">Description</label><textarea name="description" class="form-control" rows="3" required>Complete Exercise 4.2, Questions 1–8.</textarea></div><div class="col-12"><label class="form-label">Due Date</label><input name="due" type="date" class="form-control" required></div></div></div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal" type="button">Cancel</button><button class="btn btn-brand">Publish Homework</button></div></form>`);}
  function paymentModal(){const s=currentChild(),f=feeFor(s.id);openModal(`<div class="modal-header"><div><small class="eyebrow">DEMO PAYMENT</small><h2 class="modal-title">${money(f.nextInstallment)}</h2></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-warning border-0"><i class="bi bi-info-circle me-2"></i>Demo payment — no actual transaction will occur.</div><label class="form-label">Payment method</label><div class="d-grid gap-2">${['UPI','Debit / Credit Card','Net Banking'].map((x,i)=>`<label class="panel p-3"><input type="radio" name="payMethod" ${i===0?'checked':''}> <span class="ms-2 fw-semibold">${x}</span></label>`).join("")}</div></div><div class="modal-footer"><button class="btn btn-brand w-100" data-action="confirm-payment"><span class="pay-label">Pay ${money(f.nextInstallment)}</span></button></div>`);}
  function completePayment(button){button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Processing demo payment...';setTimeout(()=>{const s=currentChild(),f=feeFor(s.id);state.payments[s.id]={amount:f.nextInstallment,receipt:"LPS-REC-2026-1042",paidAt:new Date().toISOString()};persist();modal.hide();showToast("Demo payment successful");renderApp();},1000);}

  document.addEventListener("change",e=>{if(e.target.id==="roleSwitcher"){state.role=e.target.value;currentView="Dashboard";persist();renderApp();}if(e.target.id==="childSwitcher"){state.childId=e.target.value;persist();renderApp();}if(["classFilter","sectionFilter"].includes(e.target.id))filterStudents();});
  document.addEventListener("input",e=>{if(e.target.id==="studentSearch")filterStudents();});
  document.addEventListener("submit",e=>{if(e.target.id==="announcementForm"){e.preventDefault();const f=new FormData(e.target);state.announcements.unshift({id:`a-${Date.now()}`,title:f.get("title"),audience:f.get("audience"),message:f.get("message"),time:"Just now"});persist();modal.hide();showToast("Announcement published");renderApp();}if(e.target.id==="homeworkForm"){e.preventDefault();const f=new FormData(e.target);const due=f.get("due");state.homework.unshift({id:`h-${Date.now()}`,className:f.get("className"),section:f.get("section"),subject:f.get("subject"),title:f.get("title"),description:f.get("description"),due:due?new Date(`${due}T00:00:00`).toLocaleDateString("en-IN",{day:"numeric",month:"short"}):"Tomorrow",createdAt:"Just now"});persist();modal.hide();showToast("Homework published successfully");renderApp();}});
  document.addEventListener("click", e => {
    const target=e.target.closest("[data-view],[data-action],[data-student],[data-attendance]");
    if(!target)return;
    if(target.dataset.view){ currentView=target.dataset.view; renderApp(); return; }
    if(target.dataset.student){ renderStudentProfile(target.dataset.student); return; }
    if(target.dataset.attendance){
      state.attendance.records[target.dataset.id]=target.dataset.attendance;
      document.querySelectorAll(`[data-id="${target.dataset.id}"]`).forEach(b=>b.classList.toggle("active",b.dataset.attendance===target.dataset.attendance));
      const sum=document.getElementById("attendanceSummary"); if(sum)sum.textContent=attendanceCount(); return;
    }
    const a=target.dataset.action;
    if(a==="mobile-menu") bootstrap.Offcanvas.getOrCreateInstance(document.getElementById("mobileNav")).show();
    if(a==="clear-filters") { document.getElementById("studentSearch").value=""; document.getElementById("classFilter").value=""; document.getElementById("sectionFilter").value=""; filterStudents(); }
    if(a==="mark-all") { D.students.filter(s=>s.className==="II"&&s.section==="A").forEach(s=>state.attendance.records[s.id]="present"); renderApp(); }
    if(a==="save-attendance") { persist(); showToast(`Attendance saved successfully · ${attendanceCount()}`); }
    if(a==="new-homework") homeworkModal();
    if(a==="new-announcement") announcementModal();
    if(a==="pay") paymentModal();
    if(a==="confirm-payment") completePayment(target);
    if(a==="receipt") showToast("Demo receipt ready to view");
    if(a==="reset" && confirm("Reset all presentation data to the original demo?")){ localStorage.removeItem(STORE); state=freshState(); currentView="Dashboard"; renderApp(); showToast("Demo data reset"); }
    if(a==="parent-more") openModal(`<div class="modal-header"><h2 class="modal-title h5">More</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="action-grid"><button class="action-tile" data-view="Fees" data-bs-dismiss="modal"><i class="bi bi-wallet2"></i>Fees</button><button class="action-tile" data-view="Timetable" data-bs-dismiss="modal"><i class="bi bi-calendar3"></i>Timetable</button><button class="action-tile" data-view="Exams" data-bs-dismiss="modal"><i class="bi bi-bar-chart"></i>Results</button><button class="action-tile" data-view="Homework" data-bs-dismiss="modal"><i class="bi bi-journal-text"></i>Homework</button></div></div>`,"modal-sm");
  });
  renderApp();
})();
